<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Okra</name>
   <tag></tag>
   <elementGuidId>24dcde2c-072e-422f-89b5-df777a720e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c7mM1c > div.wM6W7d > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c7mM1c']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e0f3565-6ff5-435f-8c2c-e22683f00382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Okra</value>
      <webElementGuid>0c1c47c8-a93c-4cde-921d-7d4831b6e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c7mM1c&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>f435dcd5-f179-46cd-a408-93be3a11bc16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c7mM1c']/div/span</value>
      <webElementGuid>0f2a3564-21fc-4ce6-9cdc-8a5bd9b349c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::span[1]</value>
      <webElementGuid>4c17fafd-7963-49a4-8fea-4ad51c450690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[2]/following::span[2]</value>
      <webElementGuid>7c2b6c6d-5ae7-46e5-8d30-a4d509bdb0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant'])[1]/preceding::span[1]</value>
      <webElementGuid>a766a05b-30c7-4484-8ed7-9760e0ac491b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[3]/preceding::span[3]</value>
      <webElementGuid>f21bf45f-8205-4580-a1e4-444f31cf4ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okra']/parent::*</value>
      <webElementGuid>03088011-fbb3-4005-8438-2b9e690475c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[3]/div/div[2]/div/div/span</value>
      <webElementGuid>27b1cd6c-c04f-4fef-8b20-929fff4cc1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Okra' or . = 'Okra')]</value>
      <webElementGuid>a18fec3f-6f5f-44db-8cd6-376573eb14dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
